version: '3.7'

networks:
  private: ~
  traefik:
    external: true

volumes:
  db:
    name: ${COMPOSE_PROJECT_NAME:-template}_db

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php7.Dockerfile
      args:
        PHP_USER: ${COMPOSE_USER:-nobody}
        PHP_GROUP: ${COMPOSE_GROUP:-nobody}
    image: ${COMPOSE_PROJECT_NAME:-template}/php
    networks:
      - private
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./www:/var/www
    labels:
      - "traefik.enable=false"

  www:
    container_name: www
    image: nginx:alpine
    networks:
      - traefik
      - private
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/var/www:ro
    labels:
      - "traefik.port=80"
      - "traefik.docker.network=traefik"
    depends_on:
      - php

  db:
    container_name: db
    image: mariadb
    env_file: .env
    networks:
      - private
    volumes:
      - db:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  mails:
    container_name: mails
    image: mailhog/mailhog
    networks:
      - traefik
      - private
    labels:
      - "traefik.port=8025"
      - "traefik.docker.network=traefik"
